### ISSUE TITLE
Ordered Namelist

### ISSUE THREAD

**Issue by Johnnyteck** [ykdojo/the-dojo-way#76]
I would love to suggest an ordered Namelist for the Dojo family readme 😅. It'll look more organized and probably a first letter index would also be great.

**Comment by ykdojo** [comment]
I'm not sure about this one.

I'd imagine this process to be pretty error-prone, and I'm not sure if it's worth the effort.

**Comment by Johnnyteck** [comment]
Yeah. I agree on that too
